<template>
  <HeroSection />
  <div class="my-10">
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga velit eius, exercitationem quam doloremque quo cupiditate inventore, ipsum quia necessitatibus placeat! Consequuntur repudiandae explicabo exercitationem. Aliquid necessitatibus similique esse tempora delectus omnis obcaecati autem hic doloremque vel dolorem sunt in optio nisi consequatur quis nostrum voluptates, quisquam reprehenderit maxime modi incidunt minima unde. Dolor est facere cumque adipisci provident totam, officiis odit, recusandae quis, repellat exercitationem placeat ipsum nam soluta iusto? Perspiciatis nam error ut neque delectus facilis illo sed culpa provident impedit suscipit architecto sint rerum, velit vel mollitia qui iure soluta corrupti autem. Beatae officia magni quisquam inventore doloremque nobis? Ratione maiores minus tenetur eaque magni error, non delectus iusto omnis aspernatur illo. Minus accusantium dolorem officia aspernatur hic sequi voluptates odit voluptate iusto repudiandae maiores mollitia reiciendis, doloremque, molestiae pariatur. Ipsam asperiores quae quisquam expedita illum iusto adipisci, ducimus commodi dolore animi cupiditate, molestiae iure? Nam mollitia inventore non accusantium. Harum unde voluptates aut itaque dolorum eum, suscipit consequuntur magni distinctio doloremque fuga aliquam ea cum iste! Est provident ducimus tenetur a earum laudantium vel commodi molestias, cupiditate iure illo voluptatum magnam, nisi dicta ex doloribus doloremque molestiae perspiciatis tempore. Voluptatem, quasi nihil sit iste odio laborum!
  </div>
  <div class="my-10">
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga velit eius, exercitationem quam doloremque quo cupiditate inventore, ipsum quia necessitatibus placeat! Consequuntur repudiandae explicabo exercitationem. Aliquid necessitatibus similique esse tempora delectus omnis obcaecati autem hic doloremque vel dolorem sunt in optio nisi consequatur quis nostrum voluptates, quisquam reprehenderit maxime modi incidunt minima unde. Dolor est facere cumque adipisci provident totam, officiis odit, recusandae quis, repellat exercitationem placeat ipsum nam soluta iusto? Perspiciatis nam error ut neque delectus facilis illo sed culpa provident impedit suscipit architecto sint rerum, velit vel mollitia qui iure soluta corrupti autem. Beatae officia magni quisquam inventore doloremque nobis? Ratione maiores minus tenetur eaque magni error, non delectus iusto omnis aspernatur illo. Minus accusantium dolorem officia aspernatur hic sequi voluptates odit voluptate iusto repudiandae maiores mollitia reiciendis, doloremque, molestiae pariatur. Ipsam asperiores quae quisquam expedita illum iusto adipisci, ducimus commodi dolore animi cupiditate, molestiae iure? Nam mollitia inventore non accusantium. Harum unde voluptates aut itaque dolorum eum, suscipit consequuntur magni distinctio doloremque fuga aliquam ea cum iste! Est provident ducimus tenetur a earum laudantium vel commodi molestias, cupiditate iure illo voluptatum magnam, nisi dicta ex doloribus doloremque molestiae perspiciatis tempore. Voluptatem, quasi nihil sit iste odio laborum!
  </div>
  <div class="my-10">
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga velit eius, exercitationem quam doloremque quo cupiditate inventore, ipsum quia necessitatibus placeat! Consequuntur repudiandae explicabo exercitationem. Aliquid necessitatibus similique esse tempora delectus omnis obcaecati autem hic doloremque vel dolorem sunt in optio nisi consequatur quis nostrum voluptates, quisquam reprehenderit maxime modi incidunt minima unde. Dolor est facere cumque adipisci provident totam, officiis odit, recusandae quis, repellat exercitationem placeat ipsum nam soluta iusto? Perspiciatis nam error ut neque delectus facilis illo sed culpa provident impedit suscipit architecto sint rerum, velit vel mollitia qui iure soluta corrupti autem. Beatae officia magni quisquam inventore doloremque nobis? Ratione maiores minus tenetur eaque magni error, non delectus iusto omnis aspernatur illo. Minus accusantium dolorem officia aspernatur hic sequi voluptates odit voluptate iusto repudiandae maiores mollitia reiciendis, doloremque, molestiae pariatur. Ipsam asperiores quae quisquam expedita illum iusto adipisci, ducimus commodi dolore animi cupiditate, molestiae iure? Nam mollitia inventore non accusantium. Harum unde voluptates aut itaque dolorum eum, suscipit consequuntur magni distinctio doloremque fuga aliquam ea cum iste! Est provident ducimus tenetur a earum laudantium vel commodi molestias, cupiditate iure illo voluptatum magnam, nisi dicta ex doloribus doloremque molestiae perspiciatis tempore. Voluptatem, quasi nihil sit iste odio laborum!
  </div>
  <div class="my-10">
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga velit eius, exercitationem quam doloremque quo cupiditate inventore, ipsum quia necessitatibus placeat! Consequuntur repudiandae explicabo exercitationem. Aliquid necessitatibus similique esse tempora delectus omnis obcaecati autem hic doloremque vel dolorem sunt in optio nisi consequatur quis nostrum voluptates, quisquam reprehenderit maxime modi incidunt minima unde. Dolor est facere cumque adipisci provident totam, officiis odit, recusandae quis, repellat exercitationem placeat ipsum nam soluta iusto? Perspiciatis nam error ut neque delectus facilis illo sed culpa provident impedit suscipit architecto sint rerum, velit vel mollitia qui iure soluta corrupti autem. Beatae officia magni quisquam inventore doloremque nobis? Ratione maiores minus tenetur eaque magni error, non delectus iusto omnis aspernatur illo. Minus accusantium dolorem officia aspernatur hic sequi voluptates odit voluptate iusto repudiandae maiores mollitia reiciendis, doloremque, molestiae pariatur. Ipsam asperiores quae quisquam expedita illum iusto adipisci, ducimus commodi dolore animi cupiditate, molestiae iure? Nam mollitia inventore non accusantium. Harum unde voluptates aut itaque dolorum eum, suscipit consequuntur magni distinctio doloremque fuga aliquam ea cum iste! Est provident ducimus tenetur a earum laudantium vel commodi molestias, cupiditate iure illo voluptatum magnam, nisi dicta ex doloribus doloremque molestiae perspiciatis tempore. Voluptatem, quasi nihil sit iste odio laborum!
  </div>
  <div class="my-10">
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga velit eius, exercitationem quam doloremque quo cupiditate inventore, ipsum quia necessitatibus placeat! Consequuntur repudiandae explicabo exercitationem. Aliquid necessitatibus similique esse tempora delectus omnis obcaecati autem hic doloremque vel dolorem sunt in optio nisi consequatur quis nostrum voluptates, quisquam reprehenderit maxime modi incidunt minima unde. Dolor est facere cumque adipisci provident totam, officiis odit, recusandae quis, repellat exercitationem placeat ipsum nam soluta iusto? Perspiciatis nam error ut neque delectus facilis illo sed culpa provident impedit suscipit architecto sint rerum, velit vel mollitia qui iure soluta corrupti autem. Beatae officia magni quisquam inventore doloremque nobis? Ratione maiores minus tenetur eaque magni error, non delectus iusto omnis aspernatur illo. Minus accusantium dolorem officia aspernatur hic sequi voluptates odit voluptate iusto repudiandae maiores mollitia reiciendis, doloremque, molestiae pariatur. Ipsam asperiores quae quisquam expedita illum iusto adipisci, ducimus commodi dolore animi cupiditate, molestiae iure? Nam mollitia inventore non accusantium. Harum unde voluptates aut itaque dolorum eum, suscipit consequuntur magni distinctio doloremque fuga aliquam ea cum iste! Est provident ducimus tenetur a earum laudantium vel commodi molestias, cupiditate iure illo voluptatum magnam, nisi dicta ex doloribus doloremque molestiae perspiciatis tempore. Voluptatem, quasi nihil sit iste odio laborum!
  </div>
  <div class="my-10">
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga velit eius, exercitationem quam doloremque quo cupiditate inventore, ipsum quia necessitatibus placeat! Consequuntur repudiandae explicabo exercitationem. Aliquid necessitatibus similique esse tempora delectus omnis obcaecati autem hic doloremque vel dolorem sunt in optio nisi consequatur quis nostrum voluptates, quisquam reprehenderit maxime modi incidunt minima unde. Dolor est facere cumque adipisci provident totam, officiis odit, recusandae quis, repellat exercitationem placeat ipsum nam soluta iusto? Perspiciatis nam error ut neque delectus facilis illo sed culpa provident impedit suscipit architecto sint rerum, velit vel mollitia qui iure soluta corrupti autem. Beatae officia magni quisquam inventore doloremque nobis? Ratione maiores minus tenetur eaque magni error, non delectus iusto omnis aspernatur illo. Minus accusantium dolorem officia aspernatur hic sequi voluptates odit voluptate iusto repudiandae maiores mollitia reiciendis, doloremque, molestiae pariatur. Ipsam asperiores quae quisquam expedita illum iusto adipisci, ducimus commodi dolore animi cupiditate, molestiae iure? Nam mollitia inventore non accusantium. Harum unde voluptates aut itaque dolorum eum, suscipit consequuntur magni distinctio doloremque fuga aliquam ea cum iste! Est provident ducimus tenetur a earum laudantium vel commodi molestias, cupiditate iure illo voluptatum magnam, nisi dicta ex doloribus doloremque molestiae perspiciatis tempore. Voluptatem, quasi nihil sit iste odio laborum!
  </div>
</template>

<script setup>
import HeroSection from '@/components/home/HeroSection.vue';


</script>